// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Views || (jb.Views = {});

  jb.Views.tumblr = Backbone.View.extend({
    initialize: function(options) {
      this.options = options;
      _.bindAll(this);
      this.$el = $(this.el);
      this.render();
    },
    render: function() {
      console.log(this.model.toJSON());
      this.$el.html(this.template(this.model.toJSON()));
      this.$el.append(jb.Templates.favicon(this.model.toJSON()));
      switch (this.model.get('data').type) {
        case 'photo':
          this.setupPhoto();
      }
    },
    setupPhoto: function() {
      var _this = this;
      _.each(this.$('.images .image'), function(el, index) {
        var $el, radius;
        $el = $(el);
        if (index <= 0) {
          return;
        }
        radius = 100;
        $el.css({
          marginLeft: Math.round(radius / 2 - Math.random() * radius),
          marginTop: Math.round(radius / 2 - Math.random() * radius)
        });
      });
    },
    template: _.template("<label>posted</label>\n<div class=\"content\">\n  <% if(data.type === 'photo'){ %>\n    <div class=\"images\">\n      <% _.each(data.photos, function (photo){ %>\n        <div class=\"image\" style=\"background-image:url('<%= photo.alt_sizes[1].url %>');\"></div>\n      <% }); %>\n    </div>\n  <% } %>\n  <% if(data.type === 'quote'){ %>\n    <blockquote><%= data.text %></blockquote>\n    <% if(data.source){ %>\n      <p class=\"source\">&mdash; <%= data.source %></p>\n    <% } %>\n  <% } %>\n</div>")
  });

}).call(this);
