// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Views || (jb.Views = {});

  jb.Views.github = Backbone.View.extend({
    className: 'block github double-width',
    initialize: function(options) {
      this.options = options;
      _.bindAll(this);
      this.$el = $(this.el);
      this.render();
    },
    render: function() {
      this.$el.html(this.template(this.model.toJSON()));
      this.$el.append(jb.Templates.favicon(this.model.toJSON()));
    },
    template: _.template("<div class=\"content\">\n  <div class=\"numbers\">\n    <span class=\"number\">&nbsp;</span>\n      <span class=\"number\">0</span>\n      <span class=\"number\">1</span>\n      <span class=\"number\">2</span>\n      <span class=\"number\">3</span>\n      <span class=\"number\">4</span>\n      <span class=\"number\">5</span>\n      <span class=\"number\">6</span>\n      <span class=\"number\">7</span>\n      <span class=\"number\">8</span>\n      <span class=\"number\">9</span>\n      <span class=\"number\">10</span>\n      <span class=\"number\">11</span>\n      <span class=\"number\">12</span>\n      <span class=\"number\">13</span>\n      <span class=\"number\">14</span>\n  </div>\n  <div class=\"message\">\n    <%= data.content %>\n  </div>\n</div>")
  });

}).call(this);
