// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Info = {
    init: function() {
      $('#blocks').isotope({
        masonry: {
          columnWidth: 80
        }
      });
    }
  };

}).call(this);
