// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Views || (jb.Views = {});

  jb.Main = {
    init: function() {
      $('.post h1').lettering('words');
    }
  };

  jb.Main.init();

}).call(this);
