// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Utils || (jb.Utils = {});

  jb.Utils.restrictNumber = function(value, min, max) {
    if (value >= min && value <= max) {
      return value;
    } else if (value <= min) {
      return min;
    } else if (value >= max) {
      return max;
    }
  };

}).call(this);
