// Generated by CoffeeScript 1.3.3
(function() {
  var jb;

  jb = window.JB || (window.JB = {});

  jb.Views || (jb.Views = {});

  jb.Views.Post = Backbone.View.extend({
    initialize: function(options) {
      this.options = options;
    }
  });

}).call(this);
